[package]
name = "cross"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.15"
ndarray-rand = "0.14"
rand = "0.8"
env_logger = "0.11.8"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "bench"
harness = false